// Generated by gencpp from file complex_com/Table.msg
// DO NOT EDIT!


#ifndef COMPLEX_COM_MESSAGE_TABLE_H
#define COMPLEX_COM_MESSAGE_TABLE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace complex_com
{
template <class ContainerAllocator>
struct Table_
{
  typedef Table_<ContainerAllocator> Type;

  Table_()
    : table()  {
    }
  Table_(const ContainerAllocator& _alloc)
    : table(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _table_type;
  _table_type table;




  typedef boost::shared_ptr< ::complex_com::Table_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::complex_com::Table_<ContainerAllocator> const> ConstPtr;

}; // struct Table_

typedef ::complex_com::Table_<std::allocator<void> > Table;

typedef boost::shared_ptr< ::complex_com::Table > TablePtr;
typedef boost::shared_ptr< ::complex_com::Table const> TableConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::complex_com::Table_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::complex_com::Table_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace complex_com

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'complex_com': ['/home/christos/catkin_ws/src/complex_com/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::complex_com::Table_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::complex_com::Table_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::complex_com::Table_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::complex_com::Table_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::complex_com::Table_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::complex_com::Table_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::complex_com::Table_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b23eaeab3fab1fc0f4aed0e9b11c7ae0";
  }

  static const char* value(const ::complex_com::Table_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb23eaeab3fab1fc0ULL;
  static const uint64_t static_value2 = 0xf4aed0e9b11c7ae0ULL;
};

template<class ContainerAllocator>
struct DataType< ::complex_com::Table_<ContainerAllocator> >
{
  static const char* value()
  {
    return "complex_com/Table";
  }

  static const char* value(const ::complex_com::Table_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::complex_com::Table_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string table\n\
";
  }

  static const char* value(const ::complex_com::Table_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::complex_com::Table_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.table);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Table_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::complex_com::Table_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::complex_com::Table_<ContainerAllocator>& v)
  {
    s << indent << "table: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.table);
  }
};

} // namespace message_operations
} // namespace ros

#endif // COMPLEX_COM_MESSAGE_TABLE_H
