; Auto-generated. Do not edit!


(cl:in-package beginner_tutorials-msg)


;//! \htmlinclude CounterGoal.msg.html

(cl:defclass <CounterGoal> (roslisp-msg-protocol:ros-message)
  ((count_up_to
    :reader count_up_to
    :initarg :count_up_to
    :type cl:integer
    :initform 0))
)

(cl:defclass CounterGoal (<CounterGoal>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <CounterGoal>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'CounterGoal)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name beginner_tutorials-msg:<CounterGoal> is deprecated: use beginner_tutorials-msg:CounterGoal instead.")))

(cl:ensure-generic-function 'count_up_to-val :lambda-list '(m))
(cl:defmethod count_up_to-val ((m <CounterGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader beginner_tutorials-msg:count_up_to-val is deprecated.  Use beginner_tutorials-msg:count_up_to instead.")
  (count_up_to m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <CounterGoal>) ostream)
  "Serializes a message object of type '<CounterGoal>"
  (cl:let* ((signed (cl:slot-value msg 'count_up_to)) (unsigned (cl:if (cl:< signed 0) (cl:+ signed 4294967296) signed)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) unsigned) ostream)
    )
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <CounterGoal>) istream)
  "Deserializes a message object of type '<CounterGoal>"
    (cl:let ((unsigned 0))
      (cl:setf (cl:ldb (cl:byte 8 0) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) unsigned) (cl:read-byte istream))
      (cl:setf (cl:slot-value msg 'count_up_to) (cl:if (cl:< unsigned 2147483648) unsigned (cl:- unsigned 4294967296))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<CounterGoal>)))
  "Returns string type for a message object of type '<CounterGoal>"
  "beginner_tutorials/CounterGoal")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'CounterGoal)))
  "Returns string type for a message object of type 'CounterGoal"
  "beginner_tutorials/CounterGoal")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<CounterGoal>)))
  "Returns md5sum for a message object of type '<CounterGoal>"
  "ffdf52d27094d6430b622a1a4113662e")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'CounterGoal)))
  "Returns md5sum for a message object of type 'CounterGoal"
  "ffdf52d27094d6430b622a1a4113662e")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<CounterGoal>)))
  "Returns full string definition for message of type '<CounterGoal>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%int32 count_up_to~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'CounterGoal)))
  "Returns full string definition for message of type 'CounterGoal"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%int32 count_up_to~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <CounterGoal>))
  (cl:+ 0
     4
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <CounterGoal>))
  "Converts a ROS message object to a list"
  (cl:list 'CounterGoal
    (cl:cons ':count_up_to (count_up_to msg))
))
