; Auto-generated. Do not edit!


(cl:in-package beginner_tutorials-msg)


;//! \htmlinclude CounterWithDelayFeedback.msg.html

(cl:defclass <CounterWithDelayFeedback> (roslisp-msg-protocol:ros-message)
  ((counts_elapsed
    :reader counts_elapsed
    :initarg :counts_elapsed
    :type cl:integer
    :initform 0))
)

(cl:defclass CounterWithDelayFeedback (<CounterWithDelayFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <CounterWithDelayFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'CounterWithDelayFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name beginner_tutorials-msg:<CounterWithDelayFeedback> is deprecated: use beginner_tutorials-msg:CounterWithDelayFeedback instead.")))

(cl:ensure-generic-function 'counts_elapsed-val :lambda-list '(m))
(cl:defmethod counts_elapsed-val ((m <CounterWithDelayFeedback>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader beginner_tutorials-msg:counts_elapsed-val is deprecated.  Use beginner_tutorials-msg:counts_elapsed instead.")
  (counts_elapsed m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <CounterWithDelayFeedback>) ostream)
  "Serializes a message object of type '<CounterWithDelayFeedback>"
  (cl:let* ((signed (cl:slot-value msg 'counts_elapsed)) (unsigned (cl:if (cl:< signed 0) (cl:+ signed 4294967296) signed)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) unsigned) ostream)
    )
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <CounterWithDelayFeedback>) istream)
  "Deserializes a message object of type '<CounterWithDelayFeedback>"
    (cl:let ((unsigned 0))
      (cl:setf (cl:ldb (cl:byte 8 0) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) unsigned) (cl:read-byte istream))
      (cl:setf (cl:slot-value msg 'counts_elapsed) (cl:if (cl:< unsigned 2147483648) unsigned (cl:- unsigned 4294967296))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<CounterWithDelayFeedback>)))
  "Returns string type for a message object of type '<CounterWithDelayFeedback>"
  "beginner_tutorials/CounterWithDelayFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'CounterWithDelayFeedback)))
  "Returns string type for a message object of type 'CounterWithDelayFeedback"
  "beginner_tutorials/CounterWithDelayFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<CounterWithDelayFeedback>)))
  "Returns md5sum for a message object of type '<CounterWithDelayFeedback>"
  "263ab814d8741f3d829a70dae8bd6d01")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'CounterWithDelayFeedback)))
  "Returns md5sum for a message object of type 'CounterWithDelayFeedback"
  "263ab814d8741f3d829a70dae8bd6d01")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<CounterWithDelayFeedback>)))
  "Returns full string definition for message of type '<CounterWithDelayFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%int32 counts_elapsed        #feedback~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'CounterWithDelayFeedback)))
  "Returns full string definition for message of type 'CounterWithDelayFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%int32 counts_elapsed        #feedback~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <CounterWithDelayFeedback>))
  (cl:+ 0
     4
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <CounterWithDelayFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'CounterWithDelayFeedback
    (cl:cons ':counts_elapsed (counts_elapsed msg))
))
