; Auto-generated. Do not edit!


(cl:in-package beginner_tutorials-msg)


;//! \htmlinclude CounterFeedback.msg.html

(cl:defclass <CounterFeedback> (roslisp-msg-protocol:ros-message)
  ((current_state
    :reader current_state
    :initarg :current_state
    :type cl:integer
    :initform 0))
)

(cl:defclass CounterFeedback (<CounterFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <CounterFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'CounterFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name beginner_tutorials-msg:<CounterFeedback> is deprecated: use beginner_tutorials-msg:CounterFeedback instead.")))

(cl:ensure-generic-function 'current_state-val :lambda-list '(m))
(cl:defmethod current_state-val ((m <CounterFeedback>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader beginner_tutorials-msg:current_state-val is deprecated.  Use beginner_tutorials-msg:current_state instead.")
  (current_state m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <CounterFeedback>) ostream)
  "Serializes a message object of type '<CounterFeedback>"
  (cl:let* ((signed (cl:slot-value msg 'current_state)) (unsigned (cl:if (cl:< signed 0) (cl:+ signed 4294967296) signed)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) unsigned) ostream)
    )
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <CounterFeedback>) istream)
  "Deserializes a message object of type '<CounterFeedback>"
    (cl:let ((unsigned 0))
      (cl:setf (cl:ldb (cl:byte 8 0) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) unsigned) (cl:read-byte istream))
      (cl:setf (cl:slot-value msg 'current_state) (cl:if (cl:< unsigned 2147483648) unsigned (cl:- unsigned 4294967296))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<CounterFeedback>)))
  "Returns string type for a message object of type '<CounterFeedback>"
  "beginner_tutorials/CounterFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'CounterFeedback)))
  "Returns string type for a message object of type 'CounterFeedback"
  "beginner_tutorials/CounterFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<CounterFeedback>)))
  "Returns md5sum for a message object of type '<CounterFeedback>"
  "c3fafd268f7cb999f1f4b4a4b04b5a08")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'CounterFeedback)))
  "Returns md5sum for a message object of type 'CounterFeedback"
  "c3fafd268f7cb999f1f4b4a4b04b5a08")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<CounterFeedback>)))
  "Returns full string definition for message of type '<CounterFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%int32 current_state~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'CounterFeedback)))
  "Returns full string definition for message of type 'CounterFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%int32 current_state~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <CounterFeedback>))
  (cl:+ 0
     4
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <CounterFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'CounterFeedback
    (cl:cons ':current_state (current_state msg))
))
