; Auto-generated. Do not edit!


(cl:in-package simple_robot_msgs-msg)


;//! \htmlinclude GetRobotPoseFeedback.msg.html

(cl:defclass <GetRobotPoseFeedback> (roslisp-msg-protocol:ros-message)
  ()
)

(cl:defclass GetRobotPoseFeedback (<GetRobotPoseFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <GetRobotPoseFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'GetRobotPoseFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name simple_robot_msgs-msg:<GetRobotPoseFeedback> is deprecated: use simple_robot_msgs-msg:GetRobotPoseFeedback instead.")))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <GetRobotPoseFeedback>) ostream)
  "Serializes a message object of type '<GetRobotPoseFeedback>"
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <GetRobotPoseFeedback>) istream)
  "Deserializes a message object of type '<GetRobotPoseFeedback>"
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<GetRobotPoseFeedback>)))
  "Returns string type for a message object of type '<GetRobotPoseFeedback>"
  "simple_robot_msgs/GetRobotPoseFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'GetRobotPoseFeedback)))
  "Returns string type for a message object of type 'GetRobotPoseFeedback"
  "simple_robot_msgs/GetRobotPoseFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<GetRobotPoseFeedback>)))
  "Returns md5sum for a message object of type '<GetRobotPoseFeedback>"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'GetRobotPoseFeedback)))
  "Returns md5sum for a message object of type 'GetRobotPoseFeedback"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<GetRobotPoseFeedback>)))
  "Returns full string definition for message of type '<GetRobotPoseFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'GetRobotPoseFeedback)))
  "Returns full string definition for message of type 'GetRobotPoseFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <GetRobotPoseFeedback>))
  (cl:+ 0
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <GetRobotPoseFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'GetRobotPoseFeedback
))
