; Auto-generated. Do not edit!


(cl:in-package simple_robot_msgs-msg)


;//! \htmlinclude GetRobotPoseGoal.msg.html

(cl:defclass <GetRobotPoseGoal> (roslisp-msg-protocol:ros-message)
  ()
)

(cl:defclass GetRobotPoseGoal (<GetRobotPoseGoal>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <GetRobotPoseGoal>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'GetRobotPoseGoal)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name simple_robot_msgs-msg:<GetRobotPoseGoal> is deprecated: use simple_robot_msgs-msg:GetRobotPoseGoal instead.")))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <GetRobotPoseGoal>) ostream)
  "Serializes a message object of type '<GetRobotPoseGoal>"
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <GetRobotPoseGoal>) istream)
  "Deserializes a message object of type '<GetRobotPoseGoal>"
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<GetRobotPoseGoal>)))
  "Returns string type for a message object of type '<GetRobotPoseGoal>"
  "simple_robot_msgs/GetRobotPoseGoal")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'GetRobotPoseGoal)))
  "Returns string type for a message object of type 'GetRobotPoseGoal"
  "simple_robot_msgs/GetRobotPoseGoal")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<GetRobotPoseGoal>)))
  "Returns md5sum for a message object of type '<GetRobotPoseGoal>"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'GetRobotPoseGoal)))
  "Returns md5sum for a message object of type 'GetRobotPoseGoal"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<GetRobotPoseGoal>)))
  "Returns full string definition for message of type '<GetRobotPoseGoal>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'GetRobotPoseGoal)))
  "Returns full string definition for message of type 'GetRobotPoseGoal"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <GetRobotPoseGoal>))
  (cl:+ 0
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <GetRobotPoseGoal>))
  "Converts a ROS message object to a list"
  (cl:list 'GetRobotPoseGoal
))
