(cl:defpackage simple_robot_msgs-msg
  (:use )
  (:export
   "<TEMPERATUREREADING>"
   "TEMPERATUREREADING"
   "<VICTIMFOUND>"
   "VICTIMFOUND"
   "<GETROBOTPOSEACTIONGOAL>"
   "GETROBOTPOSEACTIONGOAL"
   "<GETROBOTPOSEACTIONFEEDBACK>"
   "GETROBOTPOSEACTIONFEEDBACK"
   "<GETROBOTPOSERESULT>"
   "GETROBOTPOSERESULT"
   "<GETROBOTPOSEACTION>"
   "GETROBOTPOSEACTION"
   "<GETROBOTPOSEACTIONRESULT>"
   "GETROBOTPOSEACTIONRESULT"
   "<GETROBOTPOSEFEEDBACK>"
   "GETROBOTPOSEFEEDBACK"
   "<GETROBOTPOSEGOAL>"
   "GETROBOTPOSEGOAL"
  ))

