<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="smarty">

<xacro:property name="box_length" value="3"/>
<xacro:property name="box_width" value="0.2"/>
<xacro:property name="box_height" value="0.2"/>

<xacro:property name="box_length_sqrd" value="${box_length*box_length}"/>
<xacro:property name="box_width_sqrd" value="${box_width*box_width}"/>
<xacro:property name="box_height_sqrd" value="${box_height*box_height}"/>

<!--
<xacro:macro name="box_inertial_matrix" params="mass">
  <inertial>
  <mass value="${mass}" />
    <inertia
            ixx="${0.083*mass*(box_width_sqrd+box_length_sqrd)}"
            ixy="0.0"
            ixz="0.0"
            iyy="${0.083*mass*(box_length_sqrd+box_height_sqrd)}"
            iyz="0.0"
            izz="${0.083*mass*(box_width_sqrd+box_length_sqrd)}" />
  </inertial>
</xacro:macro>
-->


  <link name="base_footprint">
    <origin rpy="0 0 0" xyz="0 0 0"/>
  </link>
  <link name="smart_box">
    <visual>
      <geometry>
        <box size="${box_length} ${box_width} ${box_height}"/>
      </geometry>
      <origin rpy="0 0 0" xyz="0 0 0"/>
    </visual>
  </link>
  <joint name="joint1" type="fixed">
    <parent link="base_footprint"/>
    <child link="smart_box"/>
    <origin xyz="0 0 ${box_height}"/>
  </joint>
</robot>
