// Generated by gencpp from file beginner_tutorials/CounterFeedback.msg
// DO NOT EDIT!


#ifndef BEGINNER_TUTORIALS_MESSAGE_COUNTERFEEDBACK_H
#define BEGINNER_TUTORIALS_MESSAGE_COUNTERFEEDBACK_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace beginner_tutorials
{
template <class ContainerAllocator>
struct CounterFeedback_
{
  typedef CounterFeedback_<ContainerAllocator> Type;

  CounterFeedback_()
    : current_state(0)  {
    }
  CounterFeedback_(const ContainerAllocator& _alloc)
    : current_state(0)  {
  (void)_alloc;
    }



   typedef int32_t _current_state_type;
  _current_state_type current_state;




  typedef boost::shared_ptr< ::beginner_tutorials::CounterFeedback_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::beginner_tutorials::CounterFeedback_<ContainerAllocator> const> ConstPtr;

}; // struct CounterFeedback_

typedef ::beginner_tutorials::CounterFeedback_<std::allocator<void> > CounterFeedback;

typedef boost::shared_ptr< ::beginner_tutorials::CounterFeedback > CounterFeedbackPtr;
typedef boost::shared_ptr< ::beginner_tutorials::CounterFeedback const> CounterFeedbackConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::beginner_tutorials::CounterFeedback_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::beginner_tutorials::CounterFeedback_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace beginner_tutorials

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'beginner_tutorials': ['/home/christos/catkin_ws/src/beginner_tutorials/msg', '/home/christos/catkin_ws/devel/share/beginner_tutorials/msg'], 'actionlib_msgs': ['/opt/ros/indigo/share/actionlib_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::beginner_tutorials::CounterFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::beginner_tutorials::CounterFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::beginner_tutorials::CounterFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::beginner_tutorials::CounterFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::beginner_tutorials::CounterFeedback_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::beginner_tutorials::CounterFeedback_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::beginner_tutorials::CounterFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c3fafd268f7cb999f1f4b4a4b04b5a08";
  }

  static const char* value(const ::beginner_tutorials::CounterFeedback_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc3fafd268f7cb999ULL;
  static const uint64_t static_value2 = 0xf1f4b4a4b04b5a08ULL;
};

template<class ContainerAllocator>
struct DataType< ::beginner_tutorials::CounterFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "beginner_tutorials/CounterFeedback";
  }

  static const char* value(const ::beginner_tutorials::CounterFeedback_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::beginner_tutorials::CounterFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
int32 current_state\n\
\n\
";
  }

  static const char* value(const ::beginner_tutorials::CounterFeedback_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::beginner_tutorials::CounterFeedback_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.current_state);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct CounterFeedback_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::beginner_tutorials::CounterFeedback_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::beginner_tutorials::CounterFeedback_<ContainerAllocator>& v)
  {
    s << indent << "current_state: ";
    Printer<int32_t>::stream(s, indent + "  ", v.current_state);
  }
};

} // namespace message_operations
} // namespace ros

#endif // BEGINNER_TUTORIALS_MESSAGE_COUNTERFEEDBACK_H
