// Generated by gencpp from file beginner_tutorials/CounterGoal.msg
// DO NOT EDIT!


#ifndef BEGINNER_TUTORIALS_MESSAGE_COUNTERGOAL_H
#define BEGINNER_TUTORIALS_MESSAGE_COUNTERGOAL_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace beginner_tutorials
{
template <class ContainerAllocator>
struct CounterGoal_
{
  typedef CounterGoal_<ContainerAllocator> Type;

  CounterGoal_()
    : count_up_to(0)  {
    }
  CounterGoal_(const ContainerAllocator& _alloc)
    : count_up_to(0)  {
  (void)_alloc;
    }



   typedef int32_t _count_up_to_type;
  _count_up_to_type count_up_to;




  typedef boost::shared_ptr< ::beginner_tutorials::CounterGoal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::beginner_tutorials::CounterGoal_<ContainerAllocator> const> ConstPtr;

}; // struct CounterGoal_

typedef ::beginner_tutorials::CounterGoal_<std::allocator<void> > CounterGoal;

typedef boost::shared_ptr< ::beginner_tutorials::CounterGoal > CounterGoalPtr;
typedef boost::shared_ptr< ::beginner_tutorials::CounterGoal const> CounterGoalConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::beginner_tutorials::CounterGoal_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::beginner_tutorials::CounterGoal_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace beginner_tutorials

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'beginner_tutorials': ['/home/christos/catkin_ws/src/beginner_tutorials/msg', '/home/christos/catkin_ws/devel/share/beginner_tutorials/msg'], 'actionlib_msgs': ['/opt/ros/indigo/share/actionlib_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::beginner_tutorials::CounterGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::beginner_tutorials::CounterGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::beginner_tutorials::CounterGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::beginner_tutorials::CounterGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::beginner_tutorials::CounterGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::beginner_tutorials::CounterGoal_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::beginner_tutorials::CounterGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ffdf52d27094d6430b622a1a4113662e";
  }

  static const char* value(const ::beginner_tutorials::CounterGoal_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xffdf52d27094d643ULL;
  static const uint64_t static_value2 = 0x0b622a1a4113662eULL;
};

template<class ContainerAllocator>
struct DataType< ::beginner_tutorials::CounterGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "beginner_tutorials/CounterGoal";
  }

  static const char* value(const ::beginner_tutorials::CounterGoal_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::beginner_tutorials::CounterGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
int32 count_up_to\n\
";
  }

  static const char* value(const ::beginner_tutorials::CounterGoal_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::beginner_tutorials::CounterGoal_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.count_up_to);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct CounterGoal_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::beginner_tutorials::CounterGoal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::beginner_tutorials::CounterGoal_<ContainerAllocator>& v)
  {
    s << indent << "count_up_to: ";
    Printer<int32_t>::stream(s, indent + "  ", v.count_up_to);
  }
};

} // namespace message_operations
} // namespace ros

#endif // BEGINNER_TUTORIALS_MESSAGE_COUNTERGOAL_H
