// Generated by gencpp from file beginner_tutorials/CounterWithDelayFeedback.msg
// DO NOT EDIT!


#ifndef BEGINNER_TUTORIALS_MESSAGE_COUNTERWITHDELAYFEEDBACK_H
#define BEGINNER_TUTORIALS_MESSAGE_COUNTERWITHDELAYFEEDBACK_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace beginner_tutorials
{
template <class ContainerAllocator>
struct CounterWithDelayFeedback_
{
  typedef CounterWithDelayFeedback_<ContainerAllocator> Type;

  CounterWithDelayFeedback_()
    : counts_elapsed(0)  {
    }
  CounterWithDelayFeedback_(const ContainerAllocator& _alloc)
    : counts_elapsed(0)  {
  (void)_alloc;
    }



   typedef int32_t _counts_elapsed_type;
  _counts_elapsed_type counts_elapsed;




  typedef boost::shared_ptr< ::beginner_tutorials::CounterWithDelayFeedback_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::beginner_tutorials::CounterWithDelayFeedback_<ContainerAllocator> const> ConstPtr;

}; // struct CounterWithDelayFeedback_

typedef ::beginner_tutorials::CounterWithDelayFeedback_<std::allocator<void> > CounterWithDelayFeedback;

typedef boost::shared_ptr< ::beginner_tutorials::CounterWithDelayFeedback > CounterWithDelayFeedbackPtr;
typedef boost::shared_ptr< ::beginner_tutorials::CounterWithDelayFeedback const> CounterWithDelayFeedbackConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::beginner_tutorials::CounterWithDelayFeedback_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::beginner_tutorials::CounterWithDelayFeedback_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace beginner_tutorials

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'beginner_tutorials': ['/home/christos/catkin_ws/src/beginner_tutorials/msg', '/home/christos/catkin_ws/devel/share/beginner_tutorials/msg'], 'actionlib_msgs': ['/opt/ros/indigo/share/actionlib_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::beginner_tutorials::CounterWithDelayFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::beginner_tutorials::CounterWithDelayFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::beginner_tutorials::CounterWithDelayFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::beginner_tutorials::CounterWithDelayFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::beginner_tutorials::CounterWithDelayFeedback_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::beginner_tutorials::CounterWithDelayFeedback_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::beginner_tutorials::CounterWithDelayFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "263ab814d8741f3d829a70dae8bd6d01";
  }

  static const char* value(const ::beginner_tutorials::CounterWithDelayFeedback_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x263ab814d8741f3dULL;
  static const uint64_t static_value2 = 0x829a70dae8bd6d01ULL;
};

template<class ContainerAllocator>
struct DataType< ::beginner_tutorials::CounterWithDelayFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "beginner_tutorials/CounterWithDelayFeedback";
  }

  static const char* value(const ::beginner_tutorials::CounterWithDelayFeedback_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::beginner_tutorials::CounterWithDelayFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
int32 counts_elapsed        #feedback\n\
\n\
";
  }

  static const char* value(const ::beginner_tutorials::CounterWithDelayFeedback_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::beginner_tutorials::CounterWithDelayFeedback_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.counts_elapsed);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct CounterWithDelayFeedback_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::beginner_tutorials::CounterWithDelayFeedback_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::beginner_tutorials::CounterWithDelayFeedback_<ContainerAllocator>& v)
  {
    s << indent << "counts_elapsed: ";
    Printer<int32_t>::stream(s, indent + "  ", v.counts_elapsed);
  }
};

} // namespace message_operations
} // namespace ros

#endif // BEGINNER_TUTORIALS_MESSAGE_COUNTERWITHDELAYFEEDBACK_H
